[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Network configurations
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[profile.mainnet]
url = "${MAINNET_RPC_URL}"
private_key = "${PRIVATE_KEY}"

[profile.amoy]
url = "${AMOY_RPC_URL}"
private_key = "${PRIVATE_KEY}"