[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"  # Specify the required Solidity compiler version


# Network configurations
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"


[profile.mainnet]
url = "${MAINNET_RPC_URL}"
private_key = "${PRIVATE_KEY}"

[profile.amoy]
url = "${AMOY_RPC_URL}"
private_key = "${PRIVATE_KEY}"
